services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33066
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${192.168.1.210}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp



#  wordpress:
 #   image: wordpress:latest
  #  ports:
   #   - 8080:80
  #  restart: always
  #  environment:
  #    - WORDPRESS_DB_HOST=db
   #   - WORDPRESS_DB_USER=wordpress
   #   - WORDPRESS_DB_PASSWORD=wordpress
   #   - WORDPRESS_DB_NAME=wordpress
  dbadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
  ubuntu_pulled:
    image: vlady9988/project:latest
  apache:
    image: httpd:latest
    ports:
      - 8081:80
    restart: always
#  nginx:
#    image: nginx
#    volumes:
#      - ./templates:/etc/nginx/templates
#    ports:
#      - 80:80
volumes:
  db_data:
